# Let travis know the language it needs to run
language: python

# Mention the python version in which travis will run the app
python:
  - "3.6"


# command to install dependencies in the requirements file
# You can also install the coverage here to avoid it being in the requirements file
# It is important to avoid things like coverage, pep8 that are not required to run the app
install:
  - pip install coverage coveralls
  - pip install -r federated_trainer/requirements.txt
  - pip install -r data_owner/requirements.txt
  - pip install -r model_buyer/requirements.txt
  

# command to run tests 
# This is the script that enables travis to run the tests
# There are many ways to do dependeing on how you want travis to run and get you coverage
script: true
  - coverage run --source=. -m unittest discover -s data_owner/tests/
  - coverage run --source=. -m unittest discover -s federated_trainer/tests/
  - pylint --output-format=text federated_trainer/src



# This returns the coverage and let's coveralls know the coverage percent. 
# Note that travis will build your system and get the coverage. 
# It cannot display, therefore coveralls becomes important to get the coverage
# You can also use after_success
after_success:
  - coveralls

notifications:
  email:
    recipients:
      - rojasagustin90@gmail.com
      - zebas.graffe@gmail.com